repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.4.0
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .dockerignore .gitignore
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v2.1.0
    hooks:
    -   id: pylint
        args:
        - -d fixme
        - -d import-error
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d keyword-arg-before-vararg  # breaks py2
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.5
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v1.1.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.7
-   repo: git://github.com/Lucas-C/pre-commit-hooks-markup
    sha: v1.0.0
    hooks:
    -   id: rst-linter
