version: 2.1

orbs:
  linter: thekevjames/linter@0

jobs:
  nox:
    docker:
      - image: thekevjames/nox:2018.10.17
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-nox-{{ .Branch }}-{{ .Revision }}
          - cache-nox-{{ .Branch }}-
          - cache-nox-
      - run: nox --envdir /.nox
      - save_cache:
          key: cache-nox-{{ .Branch }}-{{ .Revision }}
          paths:
          - /.nox

  pypi:
    docker:
      - image: python:3.7.6-alpine
    steps:
      - run: pip install twine
      - checkout
      - deploy:
          name: upload to pypi
          command: |
            python setup.py sdist bdist_wheel --universal
            twine upload dist/*

  github:
    docker:
      - image: python:3.7.6-alpine
    steps:
      - run: apk add --no-cache curl git openssh-client
      - checkout
      - run:
          name: install github-release
          command: |
            curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 > github-release.tar.bz2
            tar xjf github-release.tar.bz2
            rm -f github-release.tar.bz2
      - deploy:
          name: create GitHub release
          command: |
            export PREV_RELEASE=$(git tag --sort=version:refname | tail -n2 | head -n1)
            [ -z "${PREV_RELEASE}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)

            git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' > release-description.md
            ./bin/linux/amd64/github-release release -t "${CIRCLE_TAG}"
            cat release-description.md | ./bin/linux/amd64/github-release edit -t ${CIRCLE_TAG} -d -

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
          filters:
            tags:
              only: /.*/

      - nox:
          filters:
            tags:
              only: /.*/

      - pypi:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - nox
      - github:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - nox
