version: 2.1

orbs:
  linter: thekevjames/linter@0

jobs:
  nox:
    docker:
      - image: thekevjames/nox:2018.10.17
    steps:
      - checkout
      - restore_cache:
          keys:
          - cache-nox-{{ .Branch }}-{{ .Revision }}
          - cache-nox-{{ .Branch }}-
          - cache-nox-
      - run: nox --envdir /.nox
      - save_cache:
          key: cache-nox-{{ .Branch }}-{{ .Revision }}
          paths:
          - /.nox

  pypi:
    docker:
      - image: python:3.7.6-alpine
    steps:
      - run: pip install twine
      - checkout
      - deploy:
          name: upload to pypi
          command: |
            python setup.py sdist bdist_wheel --universal
            twine upload dist/*

  github:
    docker:
      - image: debian:buster-slim
    steps:
      - run: apt update -qy
      - run: apt install -qy hub git
      - checkout
      - run:
          name: create changelog
          command: |
            export PREV_RELEASE=$(git tag --sort=version:refname | tail -n2 | head -n1)
            [ -z "${PREV_RELEASE}" ] && export PREV_RELEASE=$(git rev-list --max-parents=0 HEAD)

            echo "${CIRCLE_TAG}" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            git log ${PREV_RELEASE}..${CIRCLE_TAG} --pretty=format:'- %s' >> CHANGELOG.md
      - run: hub release create -FCHANGELOG.md "${CIRCLE_TAG}"

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
          filters:
            tags:
              only: /.*/

      - nox:
          filters:
            tags:
              only: /.*/

      - pypi:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - nox
      - github:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - linter/pre-commit
            - nox
